### ISSUE TITLE
OpenWrt composer install

### ISSUE THREAD

**Issue by petonagy** [mahadirz/smstools3-openwrt-web#1]
Hi!
How did you installed composer to OpenWrt?

I can't install it. Phar extension is missing and I can't recompile it with phar, because build fails.
"The phar extension is missing.
Install it or recompile php without --disable-phar"

Thanks for answer.

**Comment by mahadirz** [comment]
@petonagy, I didn't install the composer to OpenWrt. The composer is on the local machine, run the the composer install there, once finished upload the codes to OpenWrt

**Comment by petonagy** [comment]
Hi Mahadirz,
Thanks for reply. I did the same thing.

**Comment by andysyam** [comment]
hy .. can you give me the composer you use in your project. because I do not understand it, and I try to just show this notification .. Warning: require (vendor / autoload.php): failed to open stream: No such file or directory in /www/smstools3/public/index.php on line 12

Fatal error: require (): Failed opening required 'vendor / autoload.php' (include_path = '.: / Usr / lib / php / PEAR') in /www/smstools3/public/index.php on line 12


Thank you
